apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: prometheus
    release: r4-infrastructure
  name: {{ .Release.Name }}-pvc
  namespace: ricplt
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: local-storage
  volumeName: {{ .Release.Name }}-pv
