kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/instance: r4
    app.kubernetes.io/name: influxdb
  name: {{ .Release.Name }}-pvc
  namespace: ricplt
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  storageClassName: local-storage
  volumeName: {{ .Release.Name }}-pv

